### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by Chenyong1976** [d2cml-ai/csdid#63]
When I run "pip install dask", I get the following error message. Can you please help? Thnaks. 

(base) C:\Users\ROOTSAdmin>pip install git+https://github.com/d2cml-ai/csdid/
Collecting git+https://github.com/d2cml-ai/csdid/
  Cloning https://github.com/d2cml-ai/csdid/ to c:\users\chenyon\appdata\local\temp\pip-req-build-4rfbrhjj
  Running command git clone --filter=blob:none --quiet https://github.com/d2cml-ai/csdid/ 'C:\Users\chenyon\AppData\Local\Temp\pip-req-build-4rfbrhjj'
  warning: the following paths have collided (e.g. case-sensitive paths
  on a case-insensitive filesystem) and only one from the same
  colliding group is in the working tree:

    'README.md'
    'readme.md'
  Resolved https://github.com/d2cml-ai/csdid/ to commit 7ad721d4c384bca147ae16de84b7c5df8fe26959
  Preparing metadata (setup.py) ... done
Collecting drdid@ git+https://github.com/d2cml-ai/DRDID (from csdid==0.2.7)
  Cloning https://github.com/d2cml-ai/DRDID to c:\users\chenyon\appdata\local\temp\pip-install-9ydgy739\drdid_2c08e5591af14736af473f4dfb48c58f
  Running command git clone --filter=blob:none --quiet https://github.com/d2cml-ai/DRDID 'C:\Users\chenyon\AppData\Local\Temp\pip-install-9ydgy739\drdid_2c08e5591af14736af473f4dfb48c58f'
  Resolved https://github.com/d2cml-ai/DRDID to commit 8d26f3494225a468cde0fe3882be3b5501da9825
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (from csdid==0.2.7) (2.2.2)
Collecting numpy<=1.24.3 (from csdid==0.2.7)
  Using cached numpy-1.24.3.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\ProgramData\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\ProgramData\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\chenyon\AppData\Local\Temp\pip-build-env-g116kv0x\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\chenyon\AppData\Local\Temp\pip-build-env-g116kv0x\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\chenyon\AppData\Local\Temp\pip-build-env-g116kv0x\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by anzonyquispe** [comment]
Hi @achinmay17 @Chenyong1976 
The package now allows for latest versions of numpy. Please, let us know if you find any bug.
Best regards
Anzony Quispe

**Comment by alexanderquispe** [comment]
closing this issue as  csdid works perfectly in python 3.13
